name: verademo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      - name: Build with Maven
        run: mvn clean package

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: verademo.war
          path: target/verademo.war


  pipeline_scan:
    needs: build
    runs-on: ubuntu-latest
    name: Veracode Pipeline Scan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: verademo.war

      - name: Run Veracode Pipeline Scan
        id: pipeline-scan
        uses: veracode/Veracode-pipeline-scan-action@esd-true
        with:
          vid: ${{ secrets.VID }}
          vkey: ${{ secrets.VKEY }}
          file: "verademo.war"
          request_policy: "Veracode Recommended SCA Very Low"
          debug: 1
          fail_build: false

      - name: Upload Pipeline Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: Veracode Pipeline-Scan Results
          path: results.json


  veracode-fix:
    needs: pipeline_scan
    runs-on: ubuntu-latest
    name: Veracode Fix

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Pipeline Scan Results
        uses: actions/download-artifact@v4
        with:
          name: Veracode Pipeline-Scan Results

      - name: Create fixes from static findings
        id: convert
        uses: veracode/veracode-fix@updated_batch_fix_processing
        with:
          inputFile: results.json
          vid: ${{ secrets.VID }}
          vkey: ${{ secrets.VKEY }}
          createPR: true
          debug: false
          fixType: batch
          files: all
          cwe: '89,117,611'